### ISSUE TITLE
[suggestion] - Add length message byte to encode function

### ISSUE THREAD

**Issue by NicolasAgra** [knovichikhin/pyiso8583#12]
I think it would be very useful to add an optional parameter at function `encode` to add two bytes at the beginning of the message with the total length of it ("bigending" by the default but also parameterizable if the user needs "littleendian"). I could send you a PR with push permissions.

Best Regards.

**Comment by knovichikhin** [comment]
This is something that interface/api implementations handle separately in protocol implementation.

For example, real production software has separate settings that add 2, 4, 8, etc. bytes in little or big endian to frame TCP/IP message.

When I use this library, I personally use Twisted to handle TCP/IP clients/server. And Twisted handles it excellently at protocol level. Take a look at their "int" protocols:

https://github.com/twisted/twisted/blob/release-21.2.0-10091/src/twisted/protocols/basic.py#L649

And the int16 implementation that does exactly this:
https://github.com/twisted/twisted/blob/release-21.2.0-10091/src/twisted/protocols/basic.py#L780

I guess what I'm saying is I understand what you ask, but I think it belong in protocol implementation, not in a serializer.

**Comment by NicolasAgra** [comment]
:+1: Totally understandable, and I will give a try with twisted interface.
