### ISSUE TITLE
[Question] Migrating from Jpos

### ISSUE THREAD

**Issue by keplerk** [knovichikhin/pyiso8583#20]
Hi, i was wondering, will i encounter any problem migrating from jpos to pyiso ?
I ask cuz we have some projects using jspos but due costs optimizations we're migrating to other frameworks and the first one on the list was python, and after some research i found pyiso8583 but i'm afraid i have to do tons of reworks to my logic.
Is there any thing i have to keep in mind while using pyiso ?

**Comment by knovichikhin** [comment]
Sure, here is some pointers:

- `pyiso8583` does not support tertiary bitmaps. It's not impossible to add this, but I have not seen anybody ever use that (except Visa in their specs, but not in practise).
- `pyiso8583` serializes strings into ISO8583 blob and back. That's it. It does not understand or care about numeric fields, track2 fields, internal bitmap layout or anything like that. For example, it will de-serialize alphanumeric PAN and it's up to the higher level code to deal with it.
- `pyiso8583` does not deal with wire protocol characters and message framing. That's up to your network/protocol stack to deal with it.

**Comment by keplerk** [comment]
Thanks for your response :D

Oh then it will work without a doubt, on this case :

- We use at 2 bit maps (Amex implementation) so a 3rd bitmap won't be happen.
- No special treatment is needed right now we use the ISOMsg from Jpos that internally it's basicaly a Map<Integer, Object> to set our iso string fields so Jpos can generate a iso 8583 string that we sent 
- As part of the previous point, we handle the network/protocol that sends the iso 8583 strings to our processor

We basically just need a parser that can transform our map to an iso string and vice versa so i think pyiso it's our lucky horse :D

**Comment by knovichikhin** [comment]
Yeah, that sounds like it will fit.

A tip for debugging encoding/decoding issues. The exceptions include extra information that helps in determining parsing errors, like partially decoded message. ISO8583 decoding can sometimes fail in spectacular and unpredictable ways. This should help.

https://pyiso8583.readthedocs.io/en/latest/functions.html#exceptions
