### ISSUE TITLE
Incorrect length of BCD encoded fields

### ISSUE THREAD

**Issue by mrBuG** [knovichikhin/pyiso8583#6]
Hello,

It seems, there is issue with calcultaion lenght for binary coded decimal (BCD) values. Encoder uses length of bytes instead of use length of nibbles.

For example, the field with value `123456` should be `06123456` in the BCD coding. `06` - length of nibbles (in other words - length of value digits). However, current implementation uses the `bytes.fromhex('123456')`, and after that we get length of bytes - `3` instead of `6`. As result, our value `123456` will be encoded to `03123456`.

**Comment by knovichikhin** [comment]
Thanks for looking into it. You are correct. It should be number of nibbles.

I wonder how to handle odd data then.
If the BCD data is `12345` then it should be encoded as `05x12345` or `0512345x` where `x` is a pad value.
if the BCD data is `012345` then it should be encoded as `06012345`.

What is your expectation in this scenario?

It's probably for the best to let user decide on left/right pad and the value of the pad.

**Comment by knovichikhin** [comment]
@mrBuG I added support for the features you need. It's tested and appears to work. I'll sit on it for a bit to see if I missed something.

If you want to try it before that you can grab it from github, branch `dev-nibble`.

This is what it looks like.

Make PAN a BCD field with nibble length, pad with 0 on the left:

```
import iso8583
from iso8583.specs import default_ascii as spec
spec["2"] = {
    "data_enc": "b",
    "len_enc": "b",
    "len_type": 1,
    "len_count": "nibbles", # measure in nibbles
    "max_len": 19, # maximum 19 nibbles
    "left_pad": "0", # pad with 0
}
decoded = {
    't': '0200',
    '2': '12345678901234567'}
s, _ = iso8583.encode(decoded, spec)
print(s)
#bytearray(b'02004000000000000000\x17\x01#Eg\x89\x01#Eg')

# And back:
decoded, _ = iso8583.decode(s, spec)
print(decoded["2"])
#12345678901234567
```

Make POS entry mode a 2 byte BCD field, pad with 0 on the right:

```
import iso8583
from iso8583.specs import default_ascii as spec
spec["22"] = {
    "data_enc": "b",
    "len_enc": "b",
    "len_type": 0,
    "len_count": "nibbles", # measure in nibbles
    "max_len": 3, # 3 nibble fixed
    "right_pad": "0", # pad with 0
}
decoded = {
    't': '0200',
    '22': '051'}
s, _ = iso8583.encode(decoded, spec)
print(s)
#bytearray(b'02000000040000000000\x05\x10')

# And back
decoded, _ = iso8583.decode(s, spec)
print(decoded["22"])
#051
```

If you don't need to send odd number of nibbles then no need to specify either `left_pad` or `right_pad`.

**Comment by mrBuG** [comment]
Thank you for the support! 👍 

I will able to check it in couple of days!

**Comment by mrBuG** [comment]
@knovichikhin I've tried it in my environment. Everything looks good!

I would like to see this change in release package! :)

Thanks

**Comment by knovichikhin** [comment]
Thanks for verifying that it works.

Version 2.1.0 is on PyPI now 🚀
