### ISSUE TITLE
Failed to decode (non-hexadecimal number found in fromhex() arg at position 0)

### ISSUE THREAD

**Issue by websterAJ** [knovichikhin/pyiso8583#9]
b"\x00H`\x00\x00\x00\x00a\x10\x00\x00\x00\x00\x02\x00p8\x00\x00\x00\xc0\x00\x00\x16\x00\x00\x001\x992 v\x990\x01\x00\x00\x00%\x00\x00\x00\x00\x11\t\x17' !\x05\t00000004100000000000002"
Traceback (most recent call last):
  File "server.py", line 18, in <module>
    decoded, encoded = iso8583.decode(peticion, spec)
  File "/home/userr/.local/lib/python3.8/site-packages/iso8583/decoder.py", line 114, in decode
    idx = _decode_bitmaps(s, doc_dec, doc_enc, idx, spec, fields)
  File "/home/user/.local/lib/python3.8/site-packages/iso8583/decoder.py", line 312, in _decode_bitmaps
    raise DecodeError(
iso8583.decoder.DecodeError: Failed to decode (non-hexadecimal number found in fromhex() arg at position 0): field p pos 4

**Comment by websterAJ** [comment]
Que puedo hacer en este caso?

**Comment by knovichikhin** [comment]
Make sure your specifications align with the data you receive.
From the looks of it your specifications define primary bitmap as hex char string but the data appears to be binary.
In any case, if you need more specific help you will need to provide your specifications detail.

**Comment by websterAJ** [comment]
(
 b'0048600000000061100000000002007038000000c00000160000003198961628993001000000'
 b'250000000017222431202105103030303030303034313030303030303030303030303032'
)

**Comment by knovichikhin** [comment]
Sorry, I can't help you with that as this data does not look like anything.
I suggest you to follow up with your clients/partners to help with this.
You need to ask them for the specifications, if there is any custom header(s), if there is any network header (e.g. payload length).
